version: '3.9'
services:
  client:
    build: ./client
    container_name: app-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    restart: always

  server:
    build: ./server
    container_name: app-server
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ngcash
      - JWT_TOKEN_SECRET=jwt_secret
    ports:
      - "3001:3001"
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ngcash
    restart: 'always'
